#!/bin/bash
# Amy Voice Assistant - Live Test Guide
# When to say "Astra" - Clear Instructions

echo "🎤 AMY VOICE ASSISTANT - LIVE TEST GUIDE"
echo "========================================"
echo ""
echo "🚀 STEP 1: Start the voice assistant"
echo "   Command: bash ~/amy_core/astra_listen_loop.sh"
echo ""
echo "⏱️  STEP 2: Wait for startup (about 5-10 seconds)"
echo "   You'll hear: 'Astra online.' (Amy's voice)"
echo "   Terminal shows: '[listen] waiting for wake word (Astra)...'"
echo ""
echo "🗣️  STEP 3: Say the wake word"
echo "   ⭐ NOW SAY: 'Astra' (clearly, normal volume)"
echo "   Wait for response..."
echo ""
echo "✅ STEP 4: Amy responds"
echo "   You'll hear: 'Yes?' (Amy's voice)"
echo "   Robot should: Wave hand"
echo "   Terminal shows: '[listen] wake detected'"
echo ""
echo "🗣️  STEP 5: Give your command (within 5 seconds)"
echo "   Try saying: 'What's the time?'"
echo "   Or: 'Wave hello'"
echo "   Or: 'Status'"
echo ""
echo "🎯 EXPECTED RESULT:"
echo "   - Amy speaks the time/response"
echo "   - Robot may wave again"
echo "   - Log shows your command (not 'Astro')"
echo ""
echo "🔧 TO START THE TEST:"
echo "   cd ~/amy_core && bash astra_listen_loop.sh"
echo ""
echo "🛑 TO STOP: Press Ctrl+C"
echo ""
echo "📋 DEBUG LOGS:"
echo "   tail -f ~/logs/astra_listen_*.log    # Wake word detection"
echo "   tail -f ~/logs/pipeline_*.log        # Speech processing"